### PR TITLE
CIS 1.1 updates

### LINKED ISSUE #13: Update to CIS 1.1
CIS [announced version 1.1](https://www.linkedin.com/posts/the-center-for-internet-security_update-cis-google-cloud-platform-foundation-activity-6645383946739818496-0GzK) improvement to the benchmark, that, among other things: 

> -  Moved the Kubernetes engine section to its own Google Kubernetes Engine (GKE) Benchmark
> - Updated multiple log metric and alert recommendations
> - Updated various Command Line Interface (CLI) commands in both audit and remediation sections

[The latest benchmark](https://www.cisecurity.org/benchmark/google_cloud_computing_platform/) is available for download.

### LINKED ISSUE #18: 1.09 - ./controls (NoMethodError)
I ran inspec-gcp-cis-benchmark this morning using  https://github.com/inspec/inspec-gcp/archive/v0.23.4.tar.gz. After running the test completed I got a NoMethod error on /controls/1.09-iam.rb:50:in `block (2 levels) in load_with_context': undefined method `each' for nil:NilClass (NoMethodError). I had no IAM setting with roles/cloudkms.admin. But when I do add one, I no longer get the error.  Can you please add a condition block that checks if kmsadmins are not there and then exit/skip the control?

### LINKED ISSUE #19: 1.07 IAM control (NoMethodError)
I ran inspec-gcp-cis-benchmark this morning using https://github.com/inspec/inspec-gcp/archive/v0.23.4.tar.gz After running the test completed I got a NoMethod error on ./controls/1.07-iam.rb:50:in `block (2 levels) in load_with_context': undefined method `each' for nil:NilClass (NoMethodError). I had no IAM setting with roles/sa_admin. But when I do add one, I no longer get the error. Can you please add a condition block that checks if sa_admin are not there and then exit/skip the control?

### LINKED ISSUE #21: For controls 6.2-6.7 improve error handling
Improve error handling in 6.2 - 6.7

1. If there are no databases in a project
2. If the right type of database is not found (MySQL Vs SQL Server)
3. If no database flags/settings have been set

### LINKED ISSUE #22: Does not work with inspec > 4.18.51
As discussed in https://github.com/inspec/inspec/issues/4948 , we need to refactor the helpers to make this profile work with newer versions of inspec. This has been addressed for https://github.com/GoogleCloudPlatform/inspec-gcp-pci-profile using https://github.com/GoogleCloudPlatform/inspec-gcp-pci-profile/pull/15 and similar work is required for this profile.

### PR DESCRIPTION
**Pull request by binamov**
Updates controls to CIS 1.1, fixes #13 , fixes #18 , fixes #19 , fixes #21 , fixes #22

### CODE REVIEW

**Comment by binamov** [comment]
Currently blocked by https://github.com/inspec/inspec-gcp/issues/249
